name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CMAKE_INSTALL_PREFIX: ${{ github.workspace }}/install
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: SeRoNetOpcUaBackend
        submodules: recursive
    - name: Build server with dependencies
      run: |
        mkdir -p build
        cd build
        cmake ../SeRoNetOpcUaBackend/.github/ -DCMAKE_INSTALL_PREFIX:PATH=${{ env.CMAKE_INSTALL_PREFIX }}
        cmake --build .
    - name: Test SeRoNetOpcUaBackend
      run: |
        cd build/SeRoNetOpcUaBackend-build/
        ctest --output-on-failure ${{env.ARG_CTEST}}
